const fs = require('fs');

const translationMap = {
  "Akkaraipattu": "අක්කරෙයිපත්තුව",
  "Kattankudy": "කාත්තන්කුඩි",
  "Eravur": "එරාවුර්",
  "Valaichchenai": "වාලච්චේන",
  "Kalawanchikudi": "කලවංචිකුඩි",
  "Sammanthurai": "සමන්තුරේ",
  "Pottuvil": "පොතුවිල්",
  "Nintavur": "නින්දවූර්",
  "Maha Oya": "මහ ඔය",
  "Dehiattakandiya": "දෙහිඅත්තකණ්ඩිය",
  "Padiyathalawa": "පදියතලාව",
  "Karaitivu": "කරෛතිව්",
  "Irakkamam": "ඉරක්කාමම්",
  "Navithanveli": "නාවිදන්වේලි",
  "Sainthamaruthu": "සයින්දමරුදු",
  "Alayadivembu": "අලයාඩිවෙම්බු",
  "Thirukkovil": "තිරුක්කෝවිල්",
  "Koralai Pattu": "කෝරළේ පත්තු",
  "Eravur Pattu": "එරාවුර් පත්තු",
  "Manmunai": "මන්මුනෙයි",
  "Porativu Pattu": "පෝරතිව් පත්තු",
  "Trincomalee": "ත්‍රිකුණාමලය",
  "Muthur": "මූතූර්",
  "Kinniya": "කින්නියා",
  "Kantale": "කන්තලේ",
  "Gomarankadawala": "ගෝමරන්කඩවල",
  "Morawewa": "මොරවැව",
  "Padavi Sri Pura": "පදවි ශ්‍රී පුර",
  "Seruvila": "සේරුවිල",
  "Thampalakamam": "තම්පලකාමම්",
  "Kuchchaveli": "කුච්චවේලි",
  "Verugal": "වේරුගල්",
  "Eachchilampattu": "ඊච්චිලම්පත්තු",
  "Town and Gravets": "කඩවත් සතර",
  "Jaffna": "යාපනය",
  "Nallur": "නල්ලූර්",
  "Kopay": "කෝපායි",
  "Sandilipay": "සන්දිලිපායි",
  "Chankanai": "චංකානෙයි",
  "Uduvil": "උඩුවිල්",
  "Tellippalai": "තෙල්ලිප්පලෙයි",
  "Point Pedro": "පේදුරුතුඩුව",
  "Karaveddy": "කරවෙඩ්ඩි",
  "Maruthankerney": "මරුදන්කේනි",
  "Chavakachcheri": "චාවකච්චේරිය",
  "Karainagar": "කාරෙයිනගර්",
  "Velanai": "වෙලනෙයි",
  "Kayts": "කයිට්ස්",
  "Delft": "ඩෙල්ෆ්ට්",
  "Kilinochchi": "කිලිනොච්චිය",
  "Pachchilaipalli": "පච්චිලෛපල්ලි",
  "Kandavalai": "කණ්ඩාවලෙයි",
  "Poonakary": "පූනකරි",
  "Karachchi": "කරච්චි",
  "Mannar": "මන්නාරම",
  "Nanaddan": "නානාට්ටාන්",
  "Musali": "මුසලි",
  "Manthai West": "මාන්තෙයි බටහිර",
  "Madhu": "මඩු",
  "Vavuniya": "වවුනියාව",
  "Vavuniya North": "උතුරු වවුනියාව",
  "Vengalacheddikulam": "වෙංගලචෙට්ටිකුලම්",
  "Nedunkeni": "නෙඩුන්කේනි",
  "Mullaitivu": "මුලතිව්",
  "Maritimepattu": "මුහුදුබඩපත්තුව",
  "Puthukkudiyiruppu": "පුදුකුඩිඉරිප්පු",
  "Oddusuddan": "ඔඩ්ඩුසුඩාන්",
  "Thunukkai": "තුනුක්කායි",
  "Manthai East": "මාන්තෙයි නැගෙනහිර",
  "Welioya": "වැලිඔය",
  "Anuradhapura": "අනුරාධපුරය",
  "Nuwaragam Palatha": "නුවරගම් පළාත",
  "Medawachchiya": "මැදවච්චිය",
  "Rambewa": "රඹෑව",
  "Kahatagasdigiliya": "කහටගස්දිගිලිය",
  "Horowpothana": "හොරොව්පොතාන",
  "Galenbindunuwewa": "ගලෙන්බිඳුනුවැව",
  "Mihintale": "මිහින්තලේ",
  "Thirappane": "තිරප්පනේ",
  "Kekirawa": "කැකිරාව",
  "Palagala": "පළාගල",
  "Ipalogama": "ඉපලෝගම",
  "Rajanganaya": "රාජාංගනය",
  "Nochchiyagama": "නොච්චියාගම",
  "Padaviya": "පදවිය",
  "Kebithigollewa": "කැබිතිගොල්ලෑව",
  "Mahavilachchiya": "මහවිලච්චිය",
  "Talawa": "තලාව",
  "Tambuttegama": "තඹුත්තේගම",
  "Galnewa": "ගල්නෑව",
  "Palugaswewa": "පලුගස්වැව",
  "Nachchaduwa": "නාච්චාදූව",
  "Polonnaruwa": "පොළොන්නරුව",
  "Thamankaduwa": "තමන්කඩුව",
  "Hingurakgoda": "හිඟුරක්ගොඩ",
  "Medirigiriya": "මැදිරිගිරිය",
  "Lankapura": "ලංකාපුර",
  "Welikanda": "වැලිකන්ද",
  "Dimbulagala": "දිඹුලාගල",
  "Elahera": "ඇලහැර",
  "Kurunegala": "කුරුණෑගල",
  "Weerambugedera": "වීරඹුගෙදර",
  "Malleswaram": "මල්ලෙස්වරම්",
  "Mawathagama": "මාවතගම",
  "Rideegama": "රිදීගම",
  "Ibbagamuwa": "ඉබ්බාගමුව",
  "Ganewatta": "ගනේවත්ත",
  "Wariyapola": "වාරියපොළ",
  "Kobeigane": "කොබෙයිගනේ",
  "Bingiriya": "බිංගිරිය",
  "Panduwasnuwara": "පඬුවස්නුවර",
  "Hettipola": "හෙට්ටිපොල",
  "Kuliyapitiya": "කුලියාපිටිය",
  "Udubaddawa": "උඩුබද්දාව",
  "Pannala": "පන්නල",
  "Narammala": "නාරම්මල",
  "Alawwa": "අලව්ව",
  "Polgahawela": "පොල්ගහවෙල",
  "Galgamuwa": "ගල්ගමුව",
  "Ambanpola": "අම්බන්පොළ",
  "Giriulla": "ගිරිඋල්ල",
  "Melsiripura": "මැල්සිරිපුර",
  "Rasnayakapura": "රස්නායකපුර",
  "Maho": "මහව",
  "Polpithigama": "පොල්පිතිගම",
  "Bamunukotuwa": "බමුණුකොටුව",
  "Kotawehera": "කොටවෙහෙර",
  "Puttalam": "පුත්තලම",
  "Kalpitiya": "කල්පිටිය",
  "Vantharamullai": "වන්තරමුල්ලෙයි",
  "Nawagattegama": "නවගත්තේගම",
  "Karuwalagaswewa": "කරුවලගස්වැව",
  "Mundel": "මුන්දලම",
  "Mahakumbukkadawala": "මහකුඹුක්කඩවල",
  "Anamaduwa": "ආණමඩුව",
  "Pallama": "පල්ලම",
  "Chilaw": "හලාවත",
  "Madampe": "මාදම්පේ",
  "Mahawewa": "මහවැව",
  "Nattandiya": "නාත්තන්ඩිය",
  "Wennappuwa": "වෙන්නප්පුව",
  "Dankotuwa": "දංකොටුව",
  "Wanathawilluwa": "වනතවිල්ලුව",
  "Kandy": "මහනුවර",
  "Gangawata Korale": "ගඟවට කෝරළේ",
  "Pathadumbara": "පාතදුම්බර",
  "Panvila": "පන්විල",
  "Udadumbara": "උඩදුම්බර",
  "Minipe": "මිණිපේ",
  "Medadumbara": "මැදදුම්බර",
  "Kundasale": "කුණ්ඩසාලේ",
  "Pathahewaheta": "පාතහේවාහැට",
  "Delthota": "දෙල්තොට",
  "Udapalatha": "උඩපළාත",
  "Ganga Ihala Korale": "ගඟ ඉහළ කෝරළේ",
  "Pasbage Korale": "පස්බාගේ කෝරළේ",
  "Ambagamuwa": "අඹගමුව",
  "Kotmale": "කොත්මලේ",
  "Hanguranketha": "හඟුරන්කෙත",
  "Walapane": "වලපනේ",
  "Nuwara Eliya": "නුවරඑළිය",
  "Matale": "මාතලේ",
  "Rattota": "රත්තොට",
  "Ukuwela": "උකුවෙල",
  "Naula": "නාවුල",
  "Dambulla": "දඹුල්ල",
  "Galewela": "ගලේවෙල",
  "Pallepola": "පල්ලේපොල",
  "Yatawatta": "යටවත්ත",
  "Laggala Pallegama": "ලග්ගල පල්ලේගම",
  "Wilgamuwa": "විල්ගමුව",
  "Abanganga Korale": "අඹන්ගඟ කෝරළේ",
  "Laggala-Pallegama": "ලග්ගල-පල්ලේගම",
  "Colombo": "කොළඹ",
  "Kolonnawa": "කොලොන්නාව",
  "Kaduwela": "කඩුවෙල",
  "Homagama": "හෝමාගම",
  "Seethawaka": "සීතාවක",
  "Padukka": "පාදුක්ක",
  "Maharagama": "මහරගම",
  "Sri Jayawardenepura Kotte": "ශ්‍රී ජයවර්ධනපුර කෝට්ටේ",
  "Thimbirigasyaya": "තිඹිරිගස්යාය",
  "Dehiwala": "දෙහිවල",
  "Ratmalana": "රත්මලාන",
  "Moratuwa": "මොරටුව",
  "Kesbewa": "කැස්බෑව",
  "Gampaha": "ගම්පහ",
  "Minuwangoda": "මිනුවන්ගොඩ",
  "Divulapitiya": "දිවුලපිටිය",
  "Mirigama": "මීරිගම",
  "Attanagalla": "අත්තනගල්ල",
  "Mahara": "මහර",
  "Dompe": "දොම්පේ",
  "Biyagama": "බියගම",
  "Kelaniya": "කැලණිය",
  "Wattala": "වත්තල",
  "Negombo": "මීගමුව",
  "Katana": "කටාන",
  "Ja-Ela": "ජා-ඇල",
  "Kalutara": "කළුතර",
  "Panadura": "පාණදුර",
  "Bandaragama": "බණ්ඩාරගම",
  "Horana": "හොරණ",
  "Ingiriya": "ඉංගිරිය",
  "Bulathsinhala": "බුලත්සිංහල",
  "Madurawela": "මදුරාවෙල",
  "Dodangoda": "දොඩංගොඩ",
  "Mathugama": "මතුගම",
  "Agalawatta": "අගලවත්ත",
  "Palindanuwara": "පාලින්දනුවර",
  "Walallawita": "වලල්ලාවිට",
  "Beruwala": "බේරුවල",
  "Payagala": "පයාගල",
  "Galle": "ගාල්ල",
  "Bope-Poddala": "බෝපේ-පෝද්දල",
  "Akmeemana": "අක්මීමන",
  "Kadawatsats": "කඩවත්සතර",
  "Habaraduwa": "හබරාදුව",
  "Imaduwa": "ඉමදුව",
  "Yakkalamulla": "යක්කලමුල්ල",
  "Karandeniya": "කරන්දෙණිය",
  "Elpitiya": "ඇල්පිටිය",
  "Niyagama": "නියාගම",
  "Thawalama": "තවලම",
  "Neluwa": "නෙළුව",
  "Hiniduma": "හිනිදුම",
  "Baddegama": "බද්දේගම",
  "Welivitiya-Divithura": "වැලිවිටිය-දිවිතුර",
  "Ambalangoda": "අම්බලන්ගොඩ",
  "Balapitiya": "බලපිටිය",
  "Bentota": "බෙන්තොට",
  "Matara": "මාතර",
  "Four Gravets": "කඩවත් සතර",
  "Devinuwara": "දෙවිනුවර",
  "Dickwella": "දික්වැල්ල",
  "Kamburupitiya": "කඹුරුපිටිය",
  "Mulatiyana": "මුලටියන",
  "Pasgoda": "පස්ගොඩ",
  "Kotapola": "කොටපොල",
  "Pitabeddara": "පිටබැද්දර",
  "Akuressa": "අකුරැස්ස",
  "Malimbada": "මාලිම්බඩ",
  "Thihagoda": "තිහගොඩ",
  "Hakmana": "හක්මන",
  "Kirinda Puhulwella": "කිරින්ද පුහුල්වැල්ල",
  "Welipitiya": "වැලිපිටිය",
  "Weligama": "වැලිගම",
  "Hambantota": "හම්බන්තොට",
  "Tangalle": "තංගල්ල",
  "Beliatta": "බෙලිඅත්ත",
  "Okewela": "ඕකේවෙල",
  "Weeraketiya": "වීරකැටිය",
  "Walasmulla": "වලස්මුල්ල",
  "Katuwana": "කටුවන",
  "Angunakolapelessa": "අඟුණකොළපැලැස්ස",
  "Ambalantota": "අම්බලන්තොට",
  "Sooriyawewa": "සූරියවැව",
  "Lunugamvehera": "ලුනුගම්වෙහෙර",
  "Tissamaharama": "තිස්සමහාරාමය"
};

const enJsonPath = 'frontend/src/locales/en.json';
const siJsonPath = 'frontend/src/locales/si.json';

const enData = JSON.parse(fs.readFileSync(enJsonPath, 'utf8'));
const siData = JSON.parse(fs.readFileSync(siJsonPath, 'utf8'));

// Go through all stations in enData and properly translate in siData
for (const [key, enName] of Object.entries(enData.stations)) {
  // Check if translation exists in the map
  if (translationMap[enName]) {
    siData.stations[key] = translationMap[enName];
  } else {
    // If no translation is in the map, and it still contains "(සිංහල)", clean it up or attempt transliteration
    let currentSi = siData.stations[key];
    if (currentSi && currentSi.includes('(සිංහල)')) {
      // It's a mixed string. We should just remove the English and make it phonetic Sinhala if possible,
      // but ideally we translated everything in the map. Let's see if any slipped through.
      let baseName = enName;
      // Convert standard english names to generic sinhala phonetic representation fallback if missing
      // (This is a safety net; the translationMap above covers 99% of them based on the script I read)
      console.log(`Missing translation for ${enName}`);
    }
  }
}

fs.writeFileSync(siJsonPath, JSON.stringify(siData, null, 2), 'utf8');
console.log("Sinhala JSON updated successfully. No more mixed english-sinhala words.");
