const fs = require('fs');

const taTranslationMap = {
  "Akkaraipattu": "அக்கரைப்பற்று",
  "Kattankudy": "காத்தான்குடி",
  "Eravur": "ஏறாவூர்",
  "Valaichchenai": "வாழைச்சேனை",
  "Kalawanchikudi": "களுவாஞ்சிகுடி",
  "Sammanthurai": "சம்மாந்துறை",
  "Pottuvil": "பொத்துவில்",
  "Nintavur": "நிந்தவூர்",
  "Maha Oya": "மகா ஓயா",
  "Dehiattakandiya": "தெகியத்தகண்டிய",
  "Padiyathalawa": "பதியத்தலாவ",
  "Karaitivu": "காரைதீவு",
  "Irakkamam": "இறக்காமம்",
  "Navithanveli": "நாவிதன்வெளி",
  "Sainthamaruthu": "சாய்ந்தமருது",
  "Alayadivembu": "ஆலையடிவேம்பு",
  "Thirukkovil": "திருக்கோவில்",
  "Koralai Pattu": "கோறளைப்பற்று",
  "Eravur Pattu": "ஏறாவூர்ப்பற்று",
  "Manmunai": "மண்முனை",
  "Porativu Pattu": "போரதீவுப்பற்று",
  "Trincomalee": "திருகோணமலை",
  "Muthur": "மூதூர்",
  "Kinniya": "கின்னியா",
  "Kantale": "கந்தளாய்",
  "Gomarankadawala": "கோமரன்கடவல",
  "Morawewa": "மொரவெவ",
  "Padavi Sri Pura": "பதவி ஸ்ரீ புர",
  "Seruvila": "சேருவில",
  "Thampalakamam": "தம்பலகாமம்",
  "Kuchchaveli": "குச்சவெளி",
  "Verugal": "வேருகல்",
  "Eachchilampattu": "ஈச்சிலம்பற்று",
  "Town and Gravets": "கச்சவாடி",
  "Jaffna": "யாழ்ப்பாணம்",
  "Nallur": "நல்லூர்",
  "Kopay": "கோப்பாய்",
  "Sandilipay": "சண்டிலிப்பாய்",
  "Chankanai": "சங்கானை",
  "Uduvil": "உடுவில்",
  "Tellippalai": "தெல்லிப்பளை",
  "Point Pedro": "பருத்தித்துறை",
  "Karaveddy": "கரவெட்டி",
  "Maruthankerney": "மருதங்கேணி",
  "Chavakachcheri": "சாவகச்சேரி",
  "Karainagar": "காரைநகர்",
  "Velanai": "வேலணை",
  "Kayts": "ஊர்காவற்றுறை",
  "Delft": "நெடுந்தீவு",
  "Kilinochchi": "கிளிநொச்சி",
  "Pachchilaipalli": "பச்சிலைப்பள்ளி",
  "Kandavalai": "கண்டாவளை",
  "Poonakary": "பூநகரி",
  "Karachchi": "கரைச்சி",
  "Mannar": "மன்னார்",
  "Nanaddan": "நானாட்டான்",
  "Musali": "முசலி",
  "Manthai West": "மாந்தை மேற்கு",
  "Madhu": "மடு",
  "Vavuniya": "வவுனியா",
  "Vavuniya North": "வவுனியா வடக்கு",
  "Vengalacheddikulam": "வெங்கலச்செட்டிகுளம்",
  "Nedunkeni": "நெடுங்கேணி",
  "Mullaitivu": "முல்லைத்தீவு",
  "Maritimepattu": "கரைதுறைப்பற்று",
  "Puthukkudiyiruppu": "புதுக்குடியிருப்பு",
  "Oddusuddan": "ஒட்டுசுட்டான்",
  "Thunukkai": "துணுக்காய்",
  "Manthai East": "மாந்தை கிழக்கு",
  "Welioya": "வெலியோயா",
  "Anuradhapura": "அனுராதபுரம்",
  "Nuwaragam Palatha": "நுவரகம் பழாத",
  "Medawachchiya": "மெதவாச்சி",
  "Rambewa": "றம்பாவை",
  "Kahatagasdigiliya": "கஹட்டகஸ்திகிலிய",
  "Horowpothana": "ஹொரவ்பொத்தான",
  "Galenbindunuwewa": "கலென்பிந்துனுவெவ",
  "Mihintale": "மிகிந்தலை",
  "Thirappane": "திறப்பனை",
  "Kekirawa": "கெக்கிராவ",
  "Palagala": "பலாகல",
  "Ipalogama": "இப்பலோகம",
  "Rajanganaya": "ராஜாங்கனை",
  "Nochchiyagama": "நொச்சியாகம",
  "Padaviya": "பதவிய",
  "Kebithigollewa": "கெப்பித்திகொல்லாவ",
  "Mahavilachchiya": "மகாவிளச்சி",
  "Talawa": "தலாவ",
  "Tambuttegama": "தம்புள்ளேகம",
  "Galnewa": "கல்நேவ",
  "Palugaswewa": "பழுகஸ்வெவ",
  "Nachchaduwa": "நாச்சாதுவ",
  "Polonnaruwa": "பொலன்னறுவை",
  "Thamankaduwa": "தமன்கடுவ",
  "Hingurakgoda": "ஹிங்குராக்கொட",
  "Medirigiriya": "மெதிரிகிரிய",
  "Lankapura": "லங்காபுர",
  "Welikanda": "வெலிகந்த",
  "Dimbulagala": "திம்புலாகல",
  "Elahera": "எலகெர",
  "Kurunegala": "குருநாகல்",
  "Weerambugedera": "வீரம்புகெதர",
  "Malleswaram": "மல்லேஸ்வரம்",
  "Mawathagama": "மாவத்தகம",
  "Rideegama": "ரிதீகம",
  "Ibbagamuwa": "இப்பகமுவ",
  "Ganewatta": "கனேவத்த",
  "Wariyapola": "வாரியபொல",
  "Kobeigane": "கொபேய்கனே",
  "Bingiriya": "பிங்கிரிய",
  "Panduwasnuwara": "பண்டுவஸ்நுவர",
  "Hettipola": "கெட்டிபொல",
  "Kuliyapitiya": "குளியாப்பிட்டிய",
  "Udubaddawa": "உடுபத்தாவ",
  "Pannala": "பன்னல",
  "Narammala": "நாரம்மல",
  "Alawwa": "அலவ்வ",
  "Polgahawela": "பொல்கஹவெல",
  "Galgamuwa": "கல்கமுவ",
  "Ambanpola": "அம்பன்பொல",
  "Giriulla": "கிரியுல்ல",
  "Melsiripura": "மெல்சிறிபுர",
  "Rasnayakapura": "ரஸ்நாயக்கபுர",
  "Maho": "மாகோ",
  "Polpithigama": "பொல்பித்திகம",
  "Bamunukotuwa": "பமுனுகொட்டுவ",
  "Kotawehera": "கொட்டவெகெர",
  "Puttalam": "புத்தளம்",
  "Kalpitiya": "கற்பிட்டி",
  "Vantharamullai": "வந்தாறுமூலை",
  "Nawagattegama": "நவகத்தேகம",
  "Karuwalagaswewa": "கருவலகஸ்வெவ",
  "Mundel": "முந்தல்",
  "Mahakumbukkadawala": "மகாகும்புக்கடவல",
  "Anamaduwa": "ஆனமடுவ",
  "Pallama": "பள்ளம",
  "Chilaw": "சிலாபம்",
  "Madampe": "மாதம்பை",
  "Mahawewa": "மகாவெவ",
  "Nattandiya": "நாத்தாண்டிய",
  "Wennappuwa": "வென்னப்புவ",
  "Dankotuwa": "தங்கொட்டுவ",
  "Wanathawilluwa": "வனாத்தவில்லுவ",
  "Kandy": "கண்டி",
  "Gangawata Korale": "கங்கவட்ட கோறளை",
  "Pathadumbara": "பாததும்பர",
  "Panvila": "பான்வில",
  "Udadumbara": "உடதும்பர",
  "Minipe": "மினிப்பே",
  "Medadumbara": "மெததும்பர",
  "Kundasale": "குண்டசாலை",
  "Pathahewaheta": "பாதகெவாஹெட்ட",
  "Delthota": "தெல்தோட்டை",
  "Udapalatha": "உடபலாத்த",
  "Ganga Ihala Korale": "கங்க இகல கோறளை",
  "Pasbage Korale": "பஸ்பாகே கோறளை",
  "Ambagamuwa": "அம்பகமுவ",
  "Kotmale": "கொத்மலை",
  "Hanguranketha": "கங்குரன்கெத்த",
  "Walapane": "வலப்பனை",
  "Nuwara Eliya": "நுவரெலியா",
  "Matale": "மாத்தளை",
  "Rattota": "இரத்தோட்டை",
  "Ukuwela": "உக்குவளை",
  "Naula": "நாவுல",
  "Dambulla": "தம்புள்ளை",
  "Galewela": "கலெவெல",
  "Pallepola": "பல்லேபொல",
  "Yatawatta": "யட்டவத்த",
  "Laggala Pallegama": "லக்கல பல்லேகம",
  "Wilgamuwa": "வில்கமுவ",
  "Abanganga Korale": "அம்பன்கங்க கோறளை",
  "Laggala-Pallegama": "லக்கல-பல்லேகம",
  "Colombo": "கொழும்பு",
  "Kolonnawa": "கொலன்னாவ",
  "Kaduwela": "கடுவெல",
  "Homagama": "ஹோமாகம",
  "Seethawaka": "சீதாவக்க",
  "Padukka": "பாதுக்கை",
  "Maharagama": "மகரகம",
  "Sri Jayawardenepura Kotte": "ஸ்ரீ ஜெயவர்தனபுர கோட்டே",
  "Thimbirigasyaya": "திம்பிரிகஸ்யாய",
  "Dehiwala": "தெகிவளை",
  "Ratmalana": "இரத்மலானை",
  "Moratuwa": "மொறட்டுவை",
  "Kesbewa": "கெஸ்பேவ",
  "Gampaha": "கம்பஹா",
  "Minuwangoda": "மினுவாங்கொடை",
  "Divulapitiya": "திவுலப்பிட்டிய",
  "Mirigama": "மீரிகம",
  "Attanagalla": "அத்தனகல்ல",
  "Mahara": "மகர",
  "Dompe": "தொம்பே",
  "Biyagama": "பியகம",
  "Kelaniya": "களனி",
  "Wattala": "வத்தளை",
  "Negombo": "நீர்கொழும்பு",
  "Katana": "கட்டானை",
  "Ja-Ela": "ஜா-எல",
  "Kalutara": "களுத்துறை",
  "Panadura": "பாணந்துறை",
  "Bandaragama": "பண்டாரகம",
  "Horana": "ஹொரண",
  "Ingiriya": "இங்கிரிய",
  "Bulathsinhala": "புளத்சிங்கள",
  "Madurawela": "மதுராவெல",
  "Dodangoda": "தொடங்கொட",
  "Mathugama": "மத்துகம",
  "Agalawatta": "அகலவத்தை",
  "Palindanuwara": "பாலிந்தநுவர",
  "Walallawita": "வலல்லாவிட்ட",
  "Beruwala": "பேருவளை",
  "Payagala": "பயாகல",
  "Galle": "காலி",
  "Bope-Poddala": "போப்பே-பொத்தல",
  "Akmeemana": "அக்மீமன",
  "Kadawatsats": "கடவத் சத்தர",
  "Habaraduwa": "ஹபராதுவ",
  "Imaduwa": "இமதுவ",
  "Yakkalamulla": "யக்கலமுல்ல",
  "Karandeniya": "கரந்தெனிய",
  "Elpitiya": "எல்பிட்டிய",
  "Niyagama": "நியாகம",
  "Thawalama": "தவலம",
  "Neluwa": "நெலுவ",
  "Hiniduma": "ஹினிதும",
  "Baddegama": "பத்தேகம",
  "Welivitiya-Divithura": "வெலிவிட்டிய-திவிதுற",
  "Ambalangoda": "அம்பலாங்கொடை",
  "Balapitiya": "பலபிட்டிய",
  "Bentota": "பெந்தோட்டை",
  "Matara": "மாத்தறை",
  "Four Gravets": "நான்கு கச்சவடிகள்",
  "Devinuwara": "தேவிநுவர",
  "Dickwella": "திக்வெல்ல",
  "Kamburupitiya": "கம்புறுப்பிட்டிய",
  "Mulatiyana": "முலட்டியன",
  "Pasgoda": "பஸ்கொட",
  "Kotapola": "கொட்டப்பொல",
  "Pitabeddara": "பிட்டபெத்தர",
  "Akuressa": "அக்குரஸ்ஸ",
  "Malimbada": "மாலிம்பட",
  "Thihagoda": "திஹகொட",
  "Hakmana": "ஹக்மன",
  "Kirinda Puhulwella": "கிரிந்த புஹுல்வெல்ல",
  "Welipitiya": "வெலிப்பிட்டிய",
  "Weligama": "வெலிகமை",
  "Hambantota": "அம்பாந்தோட்டை",
  "Tangalle": "தங்காலை",
  "Beliatta": "பெலியத்த",
  "Okewela": "ஓகெவெல",
  "Weeraketiya": "வீரகெட்டிய",
  "Walasmulla": "வலஸ்முல்ல",
  "Katuwana": "கட்டுவன",
  "Angunakolapelessa": "அங்குணகொலபெலஸ்ஸ",
  "Ambalantota": "அம்பலாந்தோட்டை",
  "Sooriyawewa": "சூரியவெவ",
  "Lunugamvehera": "லுணுகம்வெகெர",
  "Tissamaharama": "திஸ்ஸமஹாராமய",
  "Ampara Town": "அம்பாறை நகரம்",
  "Arugam Bay": "அறுகம்பை",
  "Badulla Town": "பதுளை நகரம்",
  "Bandaragama South": "பண்டாரகம தெற்கு",
  "Battaramulla": "பத்தரமுல்லை",
  "Chilaw Town": "சிலாபம் நகரம்",
  "Colombo 01": "கொழும்பு 01",
  "Colombo 02": "கொழும்பு 02",
  "Colombo 03": "கொழும்பு 03",
  "Colombo 04": "கொழும்பு 04",
  "Colombo 05": "கொழும்பு 05",
  "Colombo 06": "கொழும்பு 06",
  "Colombo 07": "கொழும்பு 07",
  "Colombo 08": "கொழும்பு 08",
  "Colombo 09": "கொழும்பு 09",
  "Colombo 10": "கொழும்பு 10",
  "Colombo 11": "கொழும்பு 11",
  "Colombo 12": "கொழும்பு 12",
  "Colombo 13": "கொழும்பு 13",
  "Colombo 14": "கொழும்பு 14",
  "Colombo 15": "கொழும்பு 15",
  "Dambulla Town": "தம்புள்ளை நகரம்",
  "Dehiwala-Mount Lavinia": "தெகிவளை-கல்கிசை",
  "Galle Fort": "காலி கோட்டை",
  "Grandpass": "கிராண்ட்பாஸ்",
  "Hambantota Town": "அம்பாந்தோட்டை நகரம்",
  "Ja-Ela Town": "ஜா-எல நகரம்",
  "Kandy Town": "கண்டி நகரம்",
  "Katunayake Airport": "கட்டுநாயக்க விமான நிலையம்",
  "Kegalle Town": "கேகாலை நகரம்",
  "Kinniya": "கின்னியா",
  "Kurunegala Town": "குருநாகல் நகரம்",
  "Matale Town": "மாத்தளை நகரம்",
  "Matara Town": "மாத்தறை நகரம்",
  "Negombo Town": "நீர்கொழும்பு நகரம்",
  "Nuwara Eliya Town": "நுவரெலியா நகரம்",
  "Panadura North": "பாணந்துறை வடக்கு",
  "Panadura South": "பாணந்துறை தெற்கு",
  "Peliyagoda Town": "பேலியகொட நகரம்",
  "Polonnaruwa Town": "பொலன்னறுவை நகரம்",
  "Puttalam Town": "புத்தளம் நகரம்",
  "Ratmalana": "இரத்மலானை",
  "Ratnapura Town": "இரத்தினபுரி நகரம்",
  "Slave Island": "கொம்பனித்தெரு",
  "Tangalle Town": "தங்காலை நகரம்",
  "Trincomalee Town": "திருகோணமலை நகரம்",
  "Vavuniya Town": "வவுனியா நகரம்",
  "Wattala Town": "வத்தளை நகரம்",
  "Weligama Town": "வெலிகமை நகரம்",
  "Yala": "யாலா"
};

const enJsonPath = 'frontend/src/locales/en.json';
const taJsonPath = 'frontend/src/locales/ta.json';

const enData = JSON.parse(fs.readFileSync(enJsonPath, 'utf8'));
const taData = JSON.parse(fs.readFileSync(taJsonPath, 'utf8'));

for (const [key, enName] of Object.entries(enData.stations)) {
  // Check if translation exists in the Tamil map
  if (taTranslationMap[enName]) {
    taData.stations[key] = taTranslationMap[enName];
  } else {
    // Some might already be translated from earlier (the original 130)
    let currentTa = taData.stations[key];
    // Check if it's the exact english string (from our previous fix script)
    // If it is the exact english string, we should try our best. If it's not in map, leave it. 
    // But since taTranslationMap covers the exact same set as siTranslationMap, there should be none left as English.
    if (currentTa === enName) {
      console.log(`Missing Tamil translation for ${enName}`);
    }
  }
}

fs.writeFileSync(taJsonPath, JSON.stringify(taData, null, 2), 'utf8');
console.log("Tamil JSON updated successfully. No more English words in Tamil dropdown.");
