export const POLICE_STATIONS = [
  "Abepura", "Achchuveli", "Adampan", "Addalachchenai", "Agalawatta", "Agarapathana", "Agbopura", "Ahangama",
  "Ahungalla", "Akaragama", "Akkaraipattu", "Akmeemana", "Akuressa", "Alawathugoda", "Alawwa", "Aluthepola",
  "Aluthgama", "Ambalangoda", "Ambalantota", "Ambanpola", "Ambathenna", "Ampara", "Anamaduwa", "Anguruwatota",
  "Anuradhapura", "Aranayaka", "Aralaganwila", "Atakalanpanna", "Athurugiriya", "Attanagalla", "Avissawella",
  "Ayagama", "Ayithiyamalai", "Badalkumbura", "Baddegama", "Badulla", "Bakamuna", "Balangoda", "Balapitiya",
  "Bambalapitiya", "Bandaragama", "Bandarawela", "Batticaloa", "Beliatta", "Beruwala", "Bibile", "Bingiriya",
  "Biyagama", "Bogawantalawa", "Bopitiya", "Boralanda", "Borella", "Bulathkohupitiya", "Bulathsinhala",
  "Buttala", "Chavakachcheri", "Cheddikulam", "Chilaw", "Chunnakam", "Cinnamon Gardens", "Colombo Central",
  "Colombo Fort", "Dambulla", "Dankotuwa", "Dedigama", "Dehiattakandiya", "Dehiowita", "Dehiwala",
  "Dela", "Dematagoda", "Deniyaya", "Deraniyagala", "Devinuwara", "Dickoya", "Dickwella", "Divulapitiya",
  "Diyatalawa", "Dodanduwa", "Dodangoda", "Dodangaslanda", "Dompe", "Eheliyagoda", "Ella", "Elpitiya",
  "Embilipitiya", "Eppawala", "Eravur", "Galenbindunuwewa", "Galewela", "Galgamuwa", "Galigamuwa", "Galle",
  "Gampaha", "Gampola", "Gandara", "Ginigathena", "Giribawa", "Giriulla", "Godakawela", "Gokarella",
  "Gomarankadawala", "Grandpass", "Habaraduwa", "Habarana", "Hakmana", "Haldummulla", "Hali-Ela", "Hambantota",
  "Hanguranketha", "Hanwella", "Haputale", "Hasalaka", "Hatton", "Hettipola", "Hikkaduwa", "Hingurakgoda",
  "Hiniduma", "Hiripitiya", "Homagama", "Horana", "Horowpathana", "Hungama", "Ibbagamuwa", "Ilavalai",
  "Iluppaikkadavai", "Imaduwa", "Ingiriya", "Ja-Ela", "Jaffna", "Kadawatha", "Kadugannawa", "Kaduruwela",
  "Kahatagasdigiliya", "Kahawatta", "Kalkudah", "Kalmunai", "Kalpitiya", "Kaltota", "Kalutara North", "Kalutara South",
  "Kaluwanchikudy", "Kamburupitiya", "Kandana", "Kandapola", "Kandy", "Kankesanthurai", "Kantale",
  "Karandeniya", "Kataragama", "Katugastota", "Katunayake", "Katuwana", "Kayts", "Kebithigollewa",
  "Kegalle", "Kekirawa", "Kelaniya", "Kilinochchi", "Kinniya", "Kiribathgoda", "Kobeigane", "Koggala",
  "Kohuwala", "Kollupitiya", "Kolonna", "Kopay", "Kosgama", "Kosgoda", "Koswatta", "Kotagala", "Kotahena",
  "Kotawila", "Kottawa", "Kuchchaveli", "Kuliyapitiya", "Kurunegala", "Kuruwita", "Lindula", "Lunugala",
  "Lunugamvehera", "Madampe", "Madurankuliya", "Maha Oya", "Maharagama", "Mahawela", "Mahiyanganaya", "Maho",
  "Malabe", "Mallawapitiya", "Manipay", "Mankulam", "Mannar", "Maradana", "Maradankadawala", "Marawila",
  "Maskeliya", "Matale", "Matara", "Mathugama", "Mattakkuliya", "Mawanella", "Mawathagama", "Medagama",
  "Medawachchiya", "Medirigiriya", "Meegahatenna", "Meegahawatta", "Meepe", "Meetiyagoda", "Middeniya",
  "Midigama", "Mihintale", "Minipe", "Minneriya", "Mirigama", "Mirihana", "Modara", "Monaragala", "Moratuwa",
  "Morawaka", "Mount Lavinia", "Mullaitivu", "Mulleriyawa", "Mundalama", "Murunkan", "Muttur", "Narammala",
  "Naula", "Nawalapitiya", "Nawagamuwa", "Negombo", "Neluwa", "Nikaweratiya", "Nilaveli", "Nittambuwa",
  "Niwitigala", "Niyagama", "Norochcholai", "Norton Bridge", "Norwood", "Nochchiyagama", "Nugegoda", "Nuwara Eliya",
  "Opanayaka", "Padaviya", "Padiyathalawa", "Padukka", "Palaly", "Pallama", "Pallewela", "Panadura North",
  "Panadura South", "Panamure", "Pannala", "Panwila", "Passara", "Payagala", "Pelmadulla", "Peliyagoda",
  "Peradeniya", "Pettah", "Pitabeddara", "Pitigala", "Point Pedro", "Polgahawela", "Polonnaruwa",
  "Polpithigama", "Pooneryn", "Pothuhera", "Pottuvil", "Pugoda", "Pulmoddai", "Pussellawa", "Puttalam",
  "Ragama", "Rajanganaya", "Rakwana", "Rambukkana", "Rangala", "Ranna", "Rathgama", "Ratnapura", "Rattota",
  "Ridigama", "Ridimaliyadda", "Ruwanwella", "Sammanthurai", "Seeduwa", "Serunuwara", "Sigiriya", "Siyambalanduwa",
  "Slave Island", "Suriyawewa", "Talangama", "Talawakele", "Tambuttegama", "Thanamalwila", "Tangalle", "Tellippalai",
  "Teldeniya", "Thawalama", "Thihagoda", "Thirukkovil", "Tissamaharama", "Trincomalee", "Udadumbara", "Udawalawa",
  "Udugama", "Uhana", "Ukuwela", "Uppuveli", "Uragasmanhandiya", "Urubokka", "Uva Paranagama", "Vaddukoddai",
  "Vakarai", "Valachchenai", "Vavuniya", "Velanai", "Vellavely", "Veyangoda",
  "Walapane", "Walasmulla", "Warakapola", "Wariyapola", "Wattala", "Wattegama", "Weeraketiya", "Weligama",
  "Weligepola", "Welikanda", "Welimada", "Welipenna", "Wellampitiya", "Wellawatte", "Wellawaya", "Wennappuwa",
  "Yakkalamulla", "Yatawatta", "Yatiyantota"
].sort();
