export const POLICE_STATIONS = [
  { id: "abanganga_korale", name: "Abanganga Korale" },
  { id: "abepura", name: "Abepura" },
  { id: "achchuveli", name: "Achchuveli" },
  { id: "adampan", name: "Adampan" },
  { id: "addalachchenai", name: "Addalachchenai" },
  { id: "agalawatta", name: "Agalawatta" },
  { id: "agarapathana", name: "Agarapathana" },
  { id: "agbopura", name: "Agbopura" },
  { id: "ahangama", name: "Ahangama" },
  { id: "ahungalla", name: "Ahungalla" },
  { id: "akaragama", name: "Akaragama" },
  { id: "akkaraipattu", name: "Akkaraipattu" },
  { id: "akmeemana", name: "Akmeemana" },
  { id: "akuressa", name: "Akuressa" },
  { id: "alawathugoda", name: "Alawathugoda" },
  { id: "alawwa", name: "Alawwa" },
  { id: "alayadivembu", name: "Alayadivembu" },
  { id: "aluthepola", name: "Aluthepola" },
  { id: "aluthgama", name: "Aluthgama" },
  { id: "ambagamuwa", name: "Ambagamuwa" },
  { id: "ambalangoda", name: "Ambalangoda" },
  { id: "ambalantota", name: "Ambalantota" },
  { id: "ambanpola", name: "Ambanpola" },
  { id: "ambathenna", name: "Ambathenna" },
  { id: "ampara", name: "Ampara" },
  { id: "ampara_town", name: "Ampara Town" },
  { id: "anamaduwa", name: "Anamaduwa" },
  { id: "angunakolapelessa", name: "Angunakolapelessa" },
  { id: "anguruwatota", name: "Anguruwatota" },
  { id: "anuradhapura", name: "Anuradhapura" },
  { id: "aralaganwila", name: "Aralaganwila" },
  { id: "aranayaka", name: "Aranayaka" },
  { id: "arugam_bay", name: "Arugam Bay" },
  { id: "athurugiriya", name: "Athurugiriya" },
  { id: "attanagalla", name: "Attanagalla" },
  { id: "avissawella", name: "Avissawella" },
  { id: "ayagama", name: "Ayagama" },
  { id: "badalkumbura", name: "Badalkumbura" },
  { id: "baddegama", name: "Baddegama" },
  { id: "badulla", name: "Badulla" },
  { id: "badulla_town", name: "Badulla Town" },
  { id: "balangoda", name: "Balangoda" },
  { id: "balapitiya", name: "Balapitiya" },
  { id: "bambalapitiya", name: "Bambalapitiya" },
  { id: "bamunukotuwa", name: "Bamunukotuwa" },
  { id: "bandaragama", name: "Bandaragama" },
  { id: "bandaragama_south", name: "Bandaragama South" },
  { id: "bandarawela", name: "Bandarawela" },
  { id: "battaramulla", name: "Battaramulla" },
  { id: "batticaloa", name: "Batticaloa" },
  { id: "beliatta", name: "Beliatta" },
  { id: "bentota", name: "Bentota" },
  { id: "beruwala", name: "Beruwala" },
  { id: "bibile", name: "Bibile" },
  { id: "bingiriya", name: "Bingiriya" },
  { id: "biyagama", name: "Biyagama" },
  { id: "bope_poddala", name: "Bope-Poddala" },
  { id: "borella", name: "Borella" },
  { id: "bulathsinhala", name: "Bulathsinhala" },
  { id: "buttala", name: "Buttala" },
  { id: "chankanai", name: "Chankanai" },
  { id: "chavakachcheri", name: "Chavakachcheri" },
  { id: "chilaw", name: "Chilaw" },
  { id: "chilaw_town", name: "Chilaw Town" },
  { id: "cinnamon_gardens", name: "Cinnamon Gardens" },
  { id: "colombo", name: "Colombo" },
  { id: "colombo_01", name: "Colombo 01" },
  { id: "colombo_02", name: "Colombo 02" },
  { id: "colombo_03", name: "Colombo 03" },
  { id: "colombo_04", name: "Colombo 04" },
  { id: "colombo_05", name: "Colombo 05" },
  { id: "colombo_06", name: "Colombo 06" },
  { id: "colombo_07", name: "Colombo 07" },
  { id: "colombo_08", name: "Colombo 08" },
  { id: "colombo_09", name: "Colombo 09" },
  { id: "colombo_10", name: "Colombo 10" },
  { id: "colombo_11", name: "Colombo 11" },
  { id: "colombo_12", name: "Colombo 12" },
  { id: "colombo_13", name: "Colombo 13" },
  { id: "colombo_14", name: "Colombo 14" },
  { id: "colombo_15", name: "Colombo 15" },
  { id: "colombo_central", name: "Colombo Central" },
  { id: "colombo_fort", name: "Colombo Fort" },
  { id: "dambulla", name: "Dambulla" },
  { id: "dambulla_town", name: "Dambulla Town" },
  { id: "dankotuwa", name: "Dankotuwa" },
  { id: "dehiattakandiya", name: "Dehiattakandiya" },
  { id: "dehiwala", name: "Dehiwala" },
  { id: "dehiwala_mount_lavinia", name: "Dehiwala-Mount Lavinia" },
  { id: "delft", name: "Delft" },
  { id: "delthota", name: "Delthota" },
  { id: "dematagoda", name: "Dematagoda" },
  { id: "devinuwara", name: "Devinuwara" },
  { id: "dickwella", name: "Dickwella" },
  { id: "dikwella", name: "Dikwella" },
  { id: "dimbulagala", name: "Dimbulagala" },
  { id: "divulapitiya", name: "Divulapitiya" },
  { id: "diyatalawa", name: "Diyatalawa" },
  { id: "dodangoda", name: "Dodangoda" },
  { id: "dompe", name: "Dompe" },
  { id: "eachchilampattu", name: "Eachchilampattu" },
  { id: "eheliyagoda", name: "Eheliyagoda" },
  { id: "elahera", name: "Elahera" },
  { id: "ella", name: "Ella" },
  { id: "elpitiya", name: "Elpitiya" },
  { id: "embilipitiya", name: "Embilipitiya" },
  { id: "eppawala", name: "Eppawala" },
  { id: "eravur", name: "Eravur" },
  { id: "eravur_pattu", name: "Eravur Pattu" },
  { id: "four_gravets", name: "Four Gravets" },
  { id: "galenbindunuwewa", name: "Galenbindunuwewa" },
  { id: "galewela", name: "Galewela" },
  { id: "galgamuwa", name: "Galgamuwa" },
  { id: "galle", name: "Galle" },
  { id: "galle_fort", name: "Galle Fort" },
  { id: "galnewa", name: "Galnewa" },
  { id: "gampaha", name: "Gampaha" },
  { id: "gampola", name: "Gampola" },
  { id: "ganewatta", name: "Ganewatta" },
  { id: "ganga_ihala_korale", name: "Ganga Ihala Korale" },
  { id: "gangawata_korale", name: "Gangawata Korale" },
  { id: "giriulla", name: "Giriulla" },
  { id: "gomarankadawala", name: "Gomarankadawala" },
  { id: "grandpass", name: "Grandpass" },
  { id: "habaraduwa", name: "Habaraduwa" },
  { id: "habarana", name: "Habarana" },
  { id: "hakmana", name: "Hakmana" },
  { id: "hambantota", name: "Hambantota" },
  { id: "hambantota_town", name: "Hambantota Town" },
  { id: "hanguranketha", name: "Hanguranketha" },
  { id: "hanwella", name: "Hanwella" },
  { id: "haputale", name: "Haputale" },
  { id: "hatton", name: "Hatton" },
  { id: "hettipola", name: "Hettipola" },
  { id: "hikkaduwa", name: "Hikkaduwa" },
  { id: "hingurakgoda", name: "Hingurakgoda" },
  { id: "hiniduma", name: "Hiniduma" },
  { id: "homagama", name: "Homagama" },
  { id: "horana", name: "Horana" },
  { id: "horowpothana", name: "Horowpothana" },
  { id: "ibbagamuwa", name: "Ibbagamuwa" },
  { id: "imaduwa", name: "Imaduwa" },
  { id: "ingiriya", name: "Ingiriya" },
  { id: "ipalogama", name: "Ipalogama" },
  { id: "irakkamam", name: "Irakkamam" },
  { id: "ja_ela", name: "Ja-Ela" },
  { id: "ja_ela_town", name: "Ja-Ela Town" },
  { id: "jaffna", name: "Jaffna" },
  { id: "kadawatha", name: "Kadawatha" },
  { id: "kadawatsats", name: "Kadawatsats" },
  { id: "kadugannawa", name: "Kadugannawa" },
  { id: "kaduwela", name: "Kaduwela" },
  { id: "kahatagasdigiliya", name: "Kahatagasdigiliya" },
  { id: "kahawatta", name: "Kahawatta" },
  { id: "kalawanchikudi", name: "Kalawanchikudi" },
  { id: "kalmunai", name: "Kalmunai" },
  { id: "kalpitiya", name: "Kalpitiya" },
  { id: "kalutara", name: "Kalutara" },
  { id: "kamburupitiya", name: "Kamburupitiya" },
  { id: "kandavalai", name: "Kandavalai" },
  { id: "kandy", name: "Kandy" },
  { id: "kandy_town", name: "Kandy Town" },
  { id: "kantale", name: "Kantale" },
  { id: "karachchi", name: "Karachchi" },
  { id: "karainagar", name: "Karainagar" },
  { id: "karaitivu", name: "Karaitivu" },
  { id: "karandeniya", name: "Karandeniya" },
  { id: "karaveddy", name: "Karaveddy" },
  { id: "karuwalagaswewa", name: "Karuwalagaswewa" },
  { id: "katana", name: "Katana" },
  { id: "kataragama", name: "Kataragama" },
  { id: "kattankudy", name: "Kattankudy" },
  { id: "katunayake", name: "Katunayake" },
  { id: "katunayake_airport", name: "Katunayake Airport" },
  { id: "katuwana", name: "Katuwana" },
  { id: "kayts", name: "Kayts" },
  { id: "kebithigollewa", name: "Kebithigollewa" },
  { id: "kegalle", name: "Kegalle" },
  { id: "kegalle_town", name: "Kegalle Town" },
  { id: "kekirawa", name: "Kekirawa" },
  { id: "kelaniya", name: "Kelaniya" },
  { id: "kesbewa", name: "Kesbewa" },
  { id: "kilinochchi", name: "Kilinochchi" },
  { id: "kinniya", name: "Kinniya" },
  { id: "kiribathgoda", name: "Kiribathgoda" },
  { id: "kirinda_puhulwella", name: "Kirinda Puhulwella" },
  { id: "kobeigane", name: "Kobeigane" },
  { id: "kollupitiya", name: "Kollupitiya" },
  { id: "kolonnawa", name: "Kolonnawa" },
  { id: "kopay", name: "Kopay" },
  { id: "koralai_pattu", name: "Koralai Pattu" },
  { id: "kotapola", name: "Kotapola" },
  { id: "kotawehera", name: "Kotawehera" },
  { id: "kotmale", name: "Kotmale" },
  { id: "kottawa", name: "Kottawa" },
  { id: "kuchchaveli", name: "Kuchchaveli" },
  { id: "kuliyapitiya", name: "Kuliyapitiya" },
  { id: "kundasale", name: "Kundasale" },
  { id: "kurunegala", name: "Kurunegala" },
  { id: "kurunegala_town", name: "Kurunegala Town" },
  { id: "laggala_pallegama", name: "Laggala Pallegama" },
  { id: "lankapura", name: "Lankapura" },
  { id: "lunugamvehera", name: "Lunugamvehera" },
  { id: "madampe", name: "Madampe" },
  { id: "madhu", name: "Madhu" },
  { id: "madurawela", name: "Madurawela" },
  { id: "maha_oya", name: "Maha Oya" },
  { id: "mahakumbukkadawala", name: "Mahakumbukkadawala" },
  { id: "mahara", name: "Mahara" },
  { id: "maharagama", name: "Maharagama" },
  { id: "mahavilachchiya", name: "Mahavilachchiya" },
  { id: "mahawewa", name: "Mahawewa" },
  { id: "maho", name: "Maho" },
  { id: "malabe", name: "Malabe" },
  { id: "malimbada", name: "Malimbada" },
  { id: "malleswaram", name: "Malleswaram" },
  { id: "manmunai", name: "Manmunai" },
  { id: "mannar", name: "Mannar" },
  { id: "manthai_east", name: "Manthai East" },
  { id: "manthai_west", name: "Manthai West" },
  { id: "maradana", name: "Maradana" },
  { id: "maritimepattu", name: "Maritimepattu" },
  { id: "maruthankerney", name: "Maruthankerney" },
  { id: "matale", name: "Matale" },
  { id: "matale_town", name: "Matale Town" },
  { id: "matara", name: "Matara" },
  { id: "matara_town", name: "Matara Town" },
  { id: "mathugama", name: "Mathugama" },
  { id: "mawanella", name: "Mawanella" },
  { id: "mawathagama", name: "Mawathagama" },
  { id: "medadumbara", name: "Medadumbara" },
  { id: "medawachchiya", name: "Medawachchiya" },
  { id: "medirigiriya", name: "Medirigiriya" },
  { id: "melsiripura", name: "Melsiripura" },
  { id: "mihintale", name: "Mihintale" },
  { id: "minipe", name: "Minipe" },
  { id: "minneriya", name: "Minneriya" },
  { id: "minuwangoda", name: "Minuwangoda" },
  { id: "mirigama", name: "Mirigama" },
  { id: "monaragala", name: "Monaragala" },
  { id: "moratuwa", name: "Moratuwa" },
  { id: "morawewa", name: "Morawewa" },
  { id: "mount_lavinia", name: "Mount Lavinia" },
  { id: "mulatiyana", name: "Mulatiyana" },
  { id: "mullaitivu", name: "Mullaitivu" },
  { id: "mundel", name: "Mundel" },
  { id: "musali", name: "Musali" },
  { id: "muthur", name: "Muthur" },
  { id: "nachchaduwa", name: "Nachchaduwa" },
  { id: "nallur", name: "Nallur" },
  { id: "nanaddan", name: "Nanaddan" },
  { id: "narammala", name: "Narammala" },
  { id: "nattandiya", name: "Nattandiya" },
  { id: "naula", name: "Naula" },
  { id: "navithanveli", name: "Navithanveli" },
  { id: "nawagattegama", name: "Nawagattegama" },
  { id: "nedunkeni", name: "Nedunkeni" },
  { id: "negombo", name: "Negombo" },
  { id: "negombo_town", name: "Negombo Town" },
  { id: "neluwa", name: "Neluwa" },
  { id: "nintavur", name: "Nintavur" },
  { id: "nittambuwa", name: "Nittambuwa" },
  { id: "niyagama", name: "Niyagama" },
  { id: "nochchiyagama", name: "Nochchiyagama" },
  { id: "nugegoda", name: "Nugegoda" },
  { id: "nuwara_eliya", name: "Nuwara Eliya" },
  { id: "nuwara_eliya_town", name: "Nuwara Eliya Town" },
  { id: "nuwaragam_palatha", name: "Nuwaragam Palatha" },
  { id: "oddusuddan", name: "Oddusuddan" },
  { id: "okewela", name: "Okewela" },
  { id: "pachchilaipalli", name: "Pachchilaipalli" },
  { id: "padavi_sri_pura", name: "Padavi Sri Pura" },
  { id: "padaviya", name: "Padaviya" },
  { id: "padiyathalawa", name: "Padiyathalawa" },
  { id: "padukka", name: "Padukka" },
  { id: "palagala", name: "Palagala" },
  { id: "palindanuwara", name: "Palindanuwara" },
  { id: "pallama", name: "Pallama" },
  { id: "pallepola", name: "Pallepola" },
  { id: "palugaswewa", name: "Palugaswewa" },
  { id: "panadura", name: "Panadura" },
  { id: "panadura_north", name: "Panadura North" },
  { id: "panadura_south", name: "Panadura South" },
  { id: "panduwasnuwara", name: "Panduwasnuwara" },
  { id: "pannala", name: "Pannala" },
  { id: "panvila", name: "Panvila" },
  { id: "pasbage_korale", name: "Pasbage Korale" },
  { id: "pasgoda", name: "Pasgoda" },
  { id: "pathadumbara", name: "Pathadumbara" },
  { id: "pathahewaheta", name: "Pathahewaheta" },
  { id: "payagala", name: "Payagala" },
  { id: "peliyagoda", name: "Peliyagoda" },
  { id: "peliyagoda_town", name: "Peliyagoda Town" },
  { id: "peradeniya", name: "Peradeniya" },
  { id: "pettah", name: "Pettah" },
  { id: "pitabeddara", name: "Pitabeddara" },
  { id: "point_pedro", name: "Point Pedro" },
  { id: "polgahawela", name: "Polgahawela" },
  { id: "polonnaruwa", name: "Polonnaruwa" },
  { id: "polonnaruwa_town", name: "Polonnaruwa Town" },
  { id: "polpithigama", name: "Polpithigama" },
  { id: "poonakary", name: "Poonakary" },
  { id: "porativu_pattu", name: "Porativu Pattu" },
  { id: "pottuvil", name: "Pottuvil" },
  { id: "puthukkudiyiruppu", name: "Puthukkudiyiruppu" },
  { id: "puttalam", name: "Puttalam" },
  { id: "puttalam_town", name: "Puttalam Town" },
  { id: "ragama", name: "Ragama" },
  { id: "rajanganaya", name: "Rajanganaya" },
  { id: "rambewa", name: "Rambewa" },
  { id: "rasnayakapura", name: "Rasnayakapura" },
  { id: "ratmalana", name: "Ratmalana" },
  { id: "ratnapura", name: "Ratnapura" },
  { id: "ratnapura_town", name: "Ratnapura Town" },
  { id: "rattota", name: "Rattota" },
  { id: "rideegama", name: "Rideegama" },
  { id: "sainthamaruthu", name: "Sainthamaruthu" },
  { id: "sammanthurai", name: "Sammanthurai" },
  { id: "sandilipay", name: "Sandilipay" },
  { id: "seeduwa", name: "Seeduwa" },
  { id: "seethawaka", name: "Seethawaka" },
  { id: "seruvila", name: "Seruvila" },
  { id: "sigiriya", name: "Sigiriya" },
  { id: "slave_island", name: "Slave Island" },
  { id: "sooriyawewa", name: "Sooriyawewa" },
  { id: "sri_jayawardenepura_kotte", name: "Sri Jayawardenepura Kotte" },
  { id: "talawa", name: "Talawa" },
  { id: "talawakele", name: "Talawakele" },
  { id: "tambuttegama", name: "Tambuttegama" },
  { id: "tangalle", name: "Tangalle" },
  { id: "tangalle_town", name: "Tangalle Town" },
  { id: "tellippalai", name: "Tellippalai" },
  { id: "thamankaduwa", name: "Thamankaduwa" },
  { id: "thampalakamam", name: "Thampalakamam" },
  { id: "thawalama", name: "Thawalama" },
  { id: "thihagoda", name: "Thihagoda" },
  { id: "thimbirigasyaya", name: "Thimbirigasyaya" },
  { id: "thirappane", name: "Thirappane" },
  { id: "thirukkovil", name: "Thirukkovil" },
  { id: "thunukkai", name: "Thunukkai" },
  { id: "tissamaharama", name: "Tissamaharama" },
  { id: "town_and_gravets", name: "Town and Gravets" },
  { id: "trincomalee", name: "Trincomalee" },
  { id: "trincomalee_town", name: "Trincomalee Town" },
  { id: "udadumbara", name: "Udadumbara" },
  { id: "udapalatha", name: "Udapalatha" },
  { id: "udubaddawa", name: "Udubaddawa" },
  { id: "uduvil", name: "Uduvil" },
  { id: "ukuwela", name: "Ukuwela" },
  { id: "valaichchenai", name: "Valaichchenai" },
  { id: "vantharamullai", name: "Vantharamullai" },
  { id: "vavuniya", name: "Vavuniya" },
  { id: "vavuniya_north", name: "Vavuniya North" },
  { id: "vavuniya_town", name: "Vavuniya Town" },
  { id: "velanai", name: "Velanai" },
  { id: "vengalacheddikulam", name: "Vengalacheddikulam" },
  { id: "verugal", name: "Verugal" },
  { id: "walallawita", name: "Walallawita" },
  { id: "walapane", name: "Walapane" },
  { id: "walasmulla", name: "Walasmulla" },
  { id: "wanathawilluwa", name: "Wanathawilluwa" },
  { id: "wariyapola", name: "Wariyapola" },
  { id: "wattala", name: "Wattala" },
  { id: "wattala_town", name: "Wattala Town" },
  { id: "weeraketiya", name: "Weeraketiya" },
  { id: "weerambugedera", name: "Weerambugedera" },
  { id: "weligama", name: "Weligama" },
  { id: "weligama_town", name: "Weligama Town" },
  { id: "welikanda", name: "Welikanda" },
  { id: "welimada", name: "Welimada" },
  { id: "welioya", name: "Welioya" },
  { id: "welipitiya", name: "Welipitiya" },
  { id: "welivitiya_divithura", name: "Welivitiya-Divithura" },
  { id: "wellawatte", name: "Wellawatte" },
  { id: "wellawaya", name: "Wellawaya" },
  { id: "wennappuwa", name: "Wennappuwa" },
  { id: "wilgamuwa", name: "Wilgamuwa" },
  { id: "yakkalamulla", name: "Yakkalamulla" },
  { id: "yala", name: "Yala" },
  { id: "yatawatta", name: "Yatawatta" }
];
